### ISSUE TITLE
i18n string issue

### ISSUE THREAD

**Issue by adamrusted** [mondeja/simple-icons-website-rs#100]
Where we're injecting multiple values into an i18n string - they appear to be in the wrong order.
![image](https://github.com/mondeja/simple-icons-website-rs/assets/1830867/1ef1279b-c8d0-4085-9ffd-cc500b58b646)
https://github.com/mondeja/simple-icons-website-rs/blob/1e0550ad645ec90862b82da6cdee85b1352be388/i18n/locales/en-US/main.ftl#L24
https://github.com/mondeja/simple-icons-website-rs/blob/1e0550ad645ec90862b82da6cdee85b1352be388/components/src/footer.rs#L100-L117

**Comment by mondeja** [comment]
I can't reproduce it and the order shouldn't matter. It is happening sometimes?

**Comment by adamrusted** [comment]
Seems to be fixed for me. I'd been switching between English and Japanese to demo the other localisation issue - and I know the strings are in a different order there, so perhaps a hangover from that?
