### ISSUE TITLE
Deprecations List

### ISSUE THREAD

**Issue by adamrusted** [mondeja/simple-icons-website-rs#128]
### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Allow users to visit a page which shows all deprecated icons in one place. Perhaps with a version filter. Doesn't need to be on main navigation, but a URL like `wasm.simpleicons.org/deprecations` would be nice!

**Comment by mondeja** [comment]
Check it at https://wasm.simpleicons.org/deprecations @adamrusted
