### ISSUE TITLE
Implementation of Preview Generator into this version of the website.

### ISSUE THREAD

**Issue by adamrusted** [mondeja/simple-icons-website-rs#55]
Assuming this will become the version of the website we use going forward, perhaps we should look to integrate the preview generator originally built by Peter? Not being entirely sure on how it'd work interactivity-wise, I'm unable to work out how much it'd take to put into place.

**Comment by mondeja** [comment]
That would be great. `leptos-router` is added as dependency yet and the current design support multiple pages dinamically, we just need to define a URL like `/preview` to load the preview instead of the grid.

**Comment by mondeja** [comment]
It's now served under https://wasm.simpleicons.org/preview or https://wasm.simpleicons.org?p
