### ISSUE TITLE
Icons with special characters in names are not displaying correctly.

### ISSUE THREAD

**Issue by adamrusted** [mondeja/simple-icons-website-rs#56]
Prime example is `ŠKODA` - which is displaying the correct label, but the special character has been trimmed to generate the slug of the icon.
![image](https://github.com/mondeja/simple-icons-website-rs/assets/1830867/4b24b688-0cbc-43e1-9eab-3c67d9d6900a)
![image](https://github.com/mondeja/simple-icons-website-rs/assets/1830867/e52282ba-b196-4601-9f01-f7956e6b9e0a)

**Comment by mondeja** [comment]
Yeah, I haven't had time to go through all of them.

The problem is that the current Rust implementation differs from the JS one, see [this TODO](https://github.com/mondeja/simple-icons-website-rs/blob/8ab41cfa16d82e4339d37d9403372c00990355c3/simple-icons/src/sdk/mod.rs#L27-L29).
