### ISSUE TITLE
Modal doesn't open for deprecated icons

### ISSUE THREAD

**Issue by adamrusted** [mondeja/simple-icons-website-rs#57]
Not sure if this is intentional, but something I've noticed is that the modal won't open for icons that're deprecated.
Modal does open [albeit broken](https://github.com/mondeja/simple-icons-website-rs/assets/1830867/7008eeb0-3de4-4fa2-967b-45b5794842c4) for icons with non-standard characters in their names.

**Comment by mondeja** [comment]
Somehow related to #56

**Comment by mondeja** [comment]
Fixed by https://github.com/mondeja/simple-icons-website-rs/commit/4fe751110d9968c874786f308489c2d4aa548094
